# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Drew Silcock
tagline:          'Note to self: think of tagline'
description:      'A blog for general stuff that I happen to want to make publicly available.'
url:              http://drewsberry.github.io
baseurl:          /

author:
  name:           'Drew Silcock'
  url:            https://twitter.com/drewsberry

paginate:         5

# Custom vars
version:          2.1.0

github:
  #repo:           https://github.com/poole/hyde
  repo:           https://github.com/drewsberry/drewsberry.github.io
