# Dependencies
markdown:         kramdown
highlighter:	  pygments
pygments_options: ['lineanchors']

kramdown:
    fenced_code_blocks: true

# Permalinks
permalink:        pretty

safe: false

# Setup
title:            Drew Silcock
tagline:          'Nebulous thoughts'
description:      'Maybe somebody, somewhere will find this useful.'
url:              http://drewsilcock.co.uk
baseurl:          /

author:
  name:           'Drew Silcock'
  #url:            https://twitter.com/drewsberry

paginate:         5

gems:
    - jekyll-redirect-from

# Custom vars
version:          1.1.0

exclude:
    - CNAME
    - Gemfile
    - Gemfile.lock
    - README.md

sitemap:
    file: "/sitemap.xml"
    exclude:
        - "/atom.xml"
    include_posts:
        - "/index.html"
    change_frequency_name: "change_frequency"
    priority_name: "priority"

github:
  user:           https://github.com/drewsberry
  repo:           https://github.com/drewsberry/drewsberry.github.io
