# Dependencies
markdown:         kramdown
highlighter:	  pygments
pygments_options: ['lineanchors']

kramdown:
    fenced_code_blocks: true

# Permalinks
permalink:        pretty

# Setup
title:            Drew Silcock
tagline:          'Tutorials, thoughts and experiences.'
description:      'Maybe somebody, somewhere will find this useful.'
url:              http://drewsberry.github.io
baseurl:          /

author:
  name:           'Drew Silcock'
  #url:            https://twitter.com/drewsberry

paginate:         1

# Custom vars
version:          1.0.1

github:
  repo:           https://github.com/drewsberry/drewsberry.github.io
