# Dependencies
markdown:         kramdown
highlighter:	  pygments
pygments_options: ['lineanchors']

kramdown:
    fenced_code_blocks: true

# Permalinks
permalink:        pretty

# Setup
title:            Drew Silcock
tagline:          'Nebulous thoughts'
description:      'Maybe somebody, somewhere will find this useful.'
url:              http://drewsilcock.co.uk
baseurl:          /

author:
  name:           'Drew Silcock'
  #url:            https://twitter.com/drewsberry

paginate:         5

# Custom vars
version:          1.0.2

github:
  repo:           https://github.com/drewsberry/drewsberry.github.io
